apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - vault
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault
  # namespace: default
spec:
  channel: beta
  name: vault
  source: operatorhubio-catalog
  sourceNamespace: olm
