releases:
- name: {{ requiredEnv "RELEASE_NAME" }}
  chart: ./{{ env "CHART_DIR" | default (requiredEnv "RELEASE_NAME") }}
  missingFileHandler: Warn
  values:
    - ./global.yaml
    - ./{{ requiredEnv "RELEASE_NAME" }}/values.yaml

helmDefaults:
  createNamespace: false
  timeout: {{ .Values | get "helmUpgradeTimeout" 300 }}
  atomic: true
