version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "_terraform"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
    reviewers:
      - "andrewozh"
