site_name: infra-platform
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Home:
      - Intro: "index.md"
      - Roadmap: "roadmap.md"
      - Learning: "learning.md"
  - Platform:
      - Architecture: "platform.md"
      - Tools: "tools.md"
      - CI/CD: ""
  - Networking:
      - TLS:
          - cert-manager: "tls/cert-manager.md"
      - Ingress:
          - ingress-nginx: ""
          - external-dns: ""
          - Kong: ""
      - Service Mesh:
          - istio: ""
      - Gateway API:
          - Kong Gateway: ""
  - Security:
      - Secrets:
          - Secrets Management: "secrets/secrets-management.md"
          - vault: "secrets/vault.md"
          - external-secrets: "secrets/external-secrets.md"
      - Tools:
          - trivy: ""
  - Observability:
      - Logging:
          - Log Management: "logs/log-management.md"
          - elasticsearch: "logs/elastic.md"
          - logstash: ""
          - kibana: ""
          - fluent-bit: ""
      - Monitoring:
          - Menitoring Setup: "metrics/monitoring-stack.md"
          - prometheus: "metrics/prometheus.md"
          - grafana: "metrics/grafana.md"
          - alertmanager: "metrics/alert-manager.md"
          - Datadog: "metrics/datadog.md"
      - Tracing: ""
  - Databases:
      - PostgreSQL:
          - PostgreSQL: "postgresql/postgresql.md"
          - CloudNativePG: "postgresql/cloudnative-pg.md"
      - Kafka:
          - Strimzi Operator: "db/kafka.md"
      - MongoDB:
          - MongoDB: "mongodb/mongodb.md"
          - MongoDB Community: "mongodb/mongodb-community.md"
      - Redis: "db/redis.md"
      - Clickhouse:
          - Clickhouse: "clickhouse/clickhouse.md"
          - Altinity Clickhouse: "clickhouse/clickhouse-altinity.md"
          - Clickhouse Cloud: "clickhouse/clickhouse-cloud.md"
  - FinOps:
      - Understanding FinOps: "finops.md"
