site_name: infra-platform
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Home:
      - Intro: "index.md"
      - Roadmap: "roadmap.md"
      - Learning: "learning.md"
  - Platform:
      - Architecture: "platform.md"
      - Tools: "tools.md"
      - CI/CD: ""
  - Networking:
      - TLS:
          - cert-manager: "tls/cert-manager.md"
      - Ingress:
          - ingress-nginx: ""
          - external-dns: ""
          - Kong: ""
      - Service Mesh:
          - istio: ""
      - Gateway API:
          - Kong Gateway: ""
  - Security:
      - Secrets:
          - vault: ""
          - external-secrets: ""
      - Tools:
          - trivy: ""
  - Observability:
      - Logging:
          - elasticsearch: "logs/elastic.md"
          - kibana: ""
          - fluent-bit: ""
      - Monitoring:
          - prometheus: ""
          - grafana: ""
          - alertmanager: ""
      - Tracing: ""
  - Databases:
      - PostgreSQL:
          - PostgreSQL: "postgresql/postgresql.md"
          - CloudNativePG: "postgresql/cloudnative-pg.md"
      - Kafka:
          - Strimzi Operator: "db/kafka.md"
      - MongoDB: "db/mongo.md"
      - Redis: "db/redis.md"
      - Clickhouse:
          - Clickhouse: "clickhouse/clickhouse.md"
          - Altinity Clickhouse: "clickhouse/clickhouse-altinity.md"
          - Clickhouse Cloud: "clickhouse/clickhouse-cloud.md"
  - FinOps:
      - Notes: ""
