site_name: infra-platform
docs_dir: docs
theme:
  name: readthedocs

nav:
  - Observability:
      - Logging:
          - Log Management: "logs/log-management.md"
          - elasticsearch: "logs/elastic.md"
          - logstash: ""
          - kibana: ""
          - fluent-bit: ""
          - fluentd: ""
      - Monitoring:
          - Menitoring Setup: "metrics/monitoring-stack.md"
          - prometheus: "metrics/prometheus.md"
          - grafana: "metrics/grafana.md"
          - alertmanager: "metrics/alert-manager.md"
          - Datadog: "metrics/datadog.md"
      - Tracing: ""
  - Databases:
      - PostgreSQL:
          - PostgreSQL: "postgresql/postgresql.md"
          - CloudNativePG: "postgresql/cloudnative-pg.md"
          - AWS RDS: ""
      - Kafka:
          - Kafka: "kafka/kafka.md"
          - Strimzi Kakfa Operator: "kafka/strimzi.md"
      - MongoDB:
          - MongoDB: "mongodb/mongodb.md"
          - MongoDB Community: "mongodb/mongodb-community.md"
          - MongoDB Atlas: ""
      - Redis:
          - Redis: "redis/redis.md"
          - AWS Elasticache: ""
      - Clickhouse:
          - Clickhouse: "clickhouse/clickhouse.md"
          - Altinity Clickhouse: "clickhouse/clickhouse-altinity.md"
          - Clickhouse Cloud: "clickhouse/clickhouse-cloud.md"
  - FinOps:
      - Understanding FinOps: "finops.md"
