# https://raw.githubusercontent.com/argoproj-labs/argocd-operator/master/deploy/subscription.yaml 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
spec:
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: '*'
  channel: alpha
  name: argocd-operator
  source: argocd-catalog
  sourceNamespace: olm
