strimzi-kafka-operator:
  dashboards:
    enabled: true
    namespace: kafka
    label: grafana_dashboard
    labelValue: "1"
    annotations:
      k8s-sidecar-target-directory: strimzi
      argocd.argoproj.io/sync-options: ServerSideApply=true
