apiVersion: v2
name: elasticsearch
version: 0.1.0
dependencies:
  - name: eck-stack
    version: 0.15.0
    repository: https://helm.elastic.co
  - name: prometheus-elasticsearch-exporter
    version: "6.7.2"
    repository: https://prometheus-community.github.io/helm-charts
