es_users:
  - login: andrew-ozhegov
    roles:
      - superuser
      - admin
  - login: jane-doe
    roles:
      - read_only

eck-stack:
  eck-elasticsearch:
    auth:
      fileRealm:
        - secretName: fluentbit-user-secret
        - secretName: elasticsearch-filerealm
      roles:
        - secretName: elasticsearch-roles
    nodeSets:
      - name: default
        count: 1
        podTemplate:
          spec:
            containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 1Gi
                  requests:
                    memory: 1Gi
        volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  eck-kibana:
    config:
      server.publicBaseUrl: https://kibana.home.lab
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      pathType: Prefix
      hosts:
        - host: kibana.home.lab
          path: /
      tls:
        enabled: true
        secretName: elk-kibana-tls-secret

prometheus-elasticsearch-exporter:
  es:
    uri: https://fluentbit:fluentbit@elasticsearch-es-http.logging.svc:9200
    sslSkipVerify: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    jobLabel: "app.kubernetes.io/name"
