## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
fluent-bit:
  esHost: elastic-stack-elasticsearch.logging.svc.cluster.local
  esPort: 9200

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # logLevel: debug
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Exclude_Path /var/log/containers/fluent-bit*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name nest
          Match *
          Operation flatten
          Nested_under kubernetes.labels
          Add_prefix kubernetes.labels.

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host {{ .Values.esHost }}
          Port {{ .Values.esPort }}
          Logstash_Format On
          Retry_Limit False
          Suppress_Type_Name On

      [OUTPUT]
          Name es
          Match host.*
          Host {{ .Values.esHost }}
          Port {{ .Values.esPort }}
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          Suppress_Type_Name On

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L

  serviceMonitor:
    enabled: true
    namespace: monitoring
