apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-roles
type: Opaque
stringData:
  roles.yml: |
    fluentbit:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names: 
            - "*"
          privileges:
            - create_index
            - create
            - index
            - write
            - manage
            - manage_ilm
      applications: []
    admin:
      cluster:
        - all
      indices:
        - names: 
            - "*"
          privileges:
            - all
      applications:
        - application: "kibana-.kibana"
          privileges:
            - all
          resources:
            - "*"
    read_only_user:
      cluster:
        - monitor
      indices:
        - names: 
            - "*"
          privileges:
            - read
            - view_index_metadata
      applications:
        - application: "kibana-.kibana"
          privileges:
            - read
          resources:
            - "*"

