kube-prometheus-stack:
  defaultRules:
    create: false
  alertmanager:
    enabled: false
  # kubernetesServiceMonitors:
  #   enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false

  commonLabels:
    app.kubernetes.io/instance: prom-stack

  kube-state-metrics:
    fullnameOverride: "kube-state-metrics"
    releaseLabel: true
    prometheus:
      monitor:
        enabled: true
        honorLabels: true
