eck-stack:
  eck-elasticsearch:
    nodeSets:
      - name: default
        count: 1
        podTemplate:
          spec:
            containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 1Gi
                  requests:
                    memory: 1Gi
  eck-kibana:
    config:
      server.publicBaseUrl: https://kibana.home.lab
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      pathType: Prefix
      hosts:
        - host: kibana.home.lab
          path: /
      tls:
        enabled: true
        secretName: elk-kibana-tls-secret
