apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-role
stringData:
  roles.yml: |
    fluentbit:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - "logstash-*"
            - "node-*"
            - "logs-*"
            - "fluentbit-*"
          privileges:
            - create_index
            - create
            - index
            - write
            - manage
            - manage_ilm
