apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrewozh/infra-apps.git
    path: _argocd-infra/
    targetRevision: main
    helm:
      releaseName: argocd
      valueFiles:
        - ../global.yaml
  destination:
    name: "in-cluster"
    namespace: argocd
