chart:
  nameOverride: argocd
  kind: None
  serviceAccount:
    create: false
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    hosts:
      - host: argocd.home.lab
        paths:
          - path: /
            service: argocd-server
            port: 80
