chart:
  nameOverride: argocd
  kind: None
  serviceAccount:
    create: false
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: argocd.home.lab
        paths:
          - path: /
            service: argocd-server
            port: 80
