apiVersion: v2
name: redis-operator
version: 0.0.1
dependencies:
  - name: redis-operator
    version: 0.21.2
    repository: https://ot-container-kit.github.io/helm-charts/
  - name: redis-cluster
    version: 0.17.0
    repository: https://ot-container-kit.github.io/helm-charts/
