cert-manager:
  crds:
    enabled: true
  prometheus:
    enabled: true
    podmonitor:
      enabled: true
      annotations:
        argocd.argoproj.io/sync-wave: "12"
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
