# https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/examples/basic.yaml
# https://cloudnative-pg.io/documentation/1.26/samples/cluster-example-with-roles.yaml
cluster:
  type: postgresql
  mode: standalone
  version:
    postgresql: "16"
  cluster:
    instances: 1
    storage:
      size: 2Gi
    roles:
      - name: dante
        ensure: present
        comment: Dante Alighieri
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: psql-role-dante
    monitoring:
      enabled: true
  backups:
    enabled: false
