{{- if eq .Values.global.env "demo" }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30081
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prom-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
{{- end -}}
