chart:
  nameOverride: kibana
  kind: None
  serviceAccount:
    create: false
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: kibana.home.lab
        paths:
          - path: /
            service: elastic-stack-kibana
            port: 5601

elasticsearch:
  global:
    kibanaEnabled: true
  master:
    masterOnly: false
    replicaCount: 1
    heapSize: 512m
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        memory: "1Gi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      jobLabel: "app.kubernetes.io/name"
  kibana:
    metrics:
      enabled: true
