elasticsearch:
  replicas: 1
  createCert: false
  minimumMasterNodes: 1
  esJavaOpts: "-Xmx128m -Xms128m" # example: "-Xmx1g -Xms1g"
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"
    limits:
      memory: "500Mi"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
