chart:
  nameOverride: vault
  kind: None
  serviceAccount:
    create: false
  ingress:
    enabled: true
    hosts:
      - host: vault.home.lab
        paths:
          - path: /
            service: vault
            port: 8200
