{
 "title": "Demo Cluster resources",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{}[1m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}