{{- range $cloud := .Values.clouds }}
{{- range $account := $cloud.accounts }}
{{- range $environment := $account.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: {{ $.Values.repo }}
          revision: main
          files:
            - path: 'applications/*/argo.yaml'
      - clusters: {}
    selector:
      matchExpressions:
      - key: destination
        operator: In
        values:
        - "all"
        - "{{ $cloud.name }}"
        - "{{ $account.name }}"
        - "{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}"
        - "{{ $cloud.name }}-{{ $environment.name }}"
        - "{{ $account.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
  template:
    metadata:
      name: {{`'{{.name}}-{{index .path.segments 1}}'`}}  # cluster-name + app-name
      labels:
        project: default
        service: {{`'{{index .path.segments 1}}'`}}  # app name from path
        type: app
    spec:
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        syncOptions:
        - CreateNamespace=true
      project: default
      source:
        repoURL: {{ $.Values.repo }}
        targetRevision: main
        path: {{`'{{.path.dir}}'`}}  # apps/app-name directory
        helm:
          releaseName: {{`'{{index .path.segments 1}}'`}}  # app-name
          ignoreMissingValueFiles: true
          valueFiles:
          - /global.yaml
          - '/{{ $cloud.name }}.yaml'
          - '/{{ $account.name }}.yaml'
          - '/{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $environment.name }}.yaml'
          - '/{{ $account.name }}-{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}.yaml'
          - {{`'values.yaml'`}}  # Default values in app directory
          - {{`'values-{{.destination}}.yaml'`}}  # Destination-specific values
      destination:
        name: {{`'{{.name}}'`}}
        namespace: {{`'{{.namespace | default (index .path.segments 1)}}'`}}  # Use namespace from argo.yaml or default to app name
  templatePatch: |
{{`
    spec:
      syncPolicy:
        {{- if and (hasKey . "autosync") .autosync }}
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        {{- end }}
        {{- if hasKey . "syncOptions" }}
        syncOptions:
        - CreateNamespace=true
        {{- range .syncOptions }}
        - {{ . }}
        {{- end }}
        {{- end }}
`}}
{{- end }}
{{- end }}
{{- end }}
