{{- range $cloud := .Values.clouds }}
{{- range $account := $cloud.accounts }}
{{- range $environment := $account.environments }}
{{ $cluster := include "argo.clusterName" (list $ $cloud.name $account.name $environment.name) }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $cluster }}"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: {{ $.Values.repo }}
          revision: main
          files:
            - path: 'applications/*/argo.yaml'
      - clusters:
          selector:
            matchLabels:
              clusterName: {{ $cluster }}
    selector:
      matchExpressions:
      - key: destination
        operator: In
        values:
        - "all"
        - "{{ $environment.name }}"
        - "{{ $account.name }}"
        - "{{ $account.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}"
        - "{{ $cloud.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
      - key: exclude
        operator: NotIn
        values:
        - "all"
        - "{{ $environment.name }}"
        - "{{ $account.name }}"
        - "{{ $account.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}"
        - "{{ $cloud.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
  template:
    metadata:
      name: {{`'{{.name}}-{{index .path.segments 1}}'`}}
      labels:
        project: default
        service: {{`'{{index .path.segments 1}}'`}}
        type: app
    spec:
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        syncOptions:
        - CreateNamespace=true
      project: default
      source:
        repoURL: {{ $.Values.repo }}
        targetRevision: main
        path: {{`'{{index .path.segments 0}}/{{index .path.segments 1}}'`}}
        helm:
          releaseName: {{`'{{index .path.segments 1}}'`}}
          ignoreMissingValueFiles: true
          valueFiles:
          - /global.yaml
          - '/{{ $environment.name }}.yaml'
          - '/{{ $account.name }}.yaml'
          - '/{{ $account.name }}-{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}.yaml'
          - values.yaml
          - {{ $environment.name }}.values.yaml
          - {{ $account.name }}.values.yaml
          - {{ $account.name }}-{{ $environment.name }}.values.yaml
          - {{ $cloud.name }}.values.yaml
          - {{ $cloud.name }}-{{ $environment.name }}.values.yaml
          - {{ $cloud.name }}-{{ $account.name }}.values.yaml
          - {{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}.values.yaml
      destination:
        name: {{`'{{.name}}'`}}
        namespace: {{`'{{.namespace | default (index .path.segments 1)}}'`}}
  templatePatch: |
{{`
    metadata:
      labels:
        {{- if hasKey . "labels" }}
        {{- range $key, $value := .labels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
        {{- end }}
    spec:
      syncPolicy:
        {{- if and (hasKey . "autosync") .autosync }}
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        {{- end }}
        {{- if hasKey . "syncOptions" }}
        syncOptions:
        - CreateNamespace=true
        {{- range .syncOptions }}
        - {{ . }}
        {{- end }}
        {{- end }}
`}}
{{- end }}
{{- end }}
{{- end }}
