{{- range $cloud := .Values.clouds }}
{{- range $account := $cloud.accounts }}
{{- range $environment := $account.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - merge:
          mergeKeys:
            - appName  # This identifies which configs belong to the same app
          generators:
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "base"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $cloud.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "cloud"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $account.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "account"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $environment.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "environment"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $cloud.name }}-{{ $account.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "cloud-account"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $cloud.name }}-{{ $environment.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "cloud-environment"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $account.name }}-{{ $environment.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "account-environment"
          - git:
              repoURL: {{ $.Values.repo }}
              revision: main
              files:
                - path: 'applications/*/{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}/argo.yaml'
              values:
                appName: {{`'{{index .path.segments 1}}'`}}
                configLevel: "full"
      - clusters: {}
    selector:
      matchExpressions:
      - key: destination
        operator: In
        values:
        - "all"
        - "{{ $cloud.name }}"
        - "{{ $account.name }}"
        - "{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}"
        - "{{ $cloud.name }}-{{ $environment.name }}"
        - "{{ $account.name }}-{{ $environment.name }}"
        - "{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}"
  template:
    metadata:
      name: {{`'{{.name}}-{{.appName}}'`}}
      labels:
        project: default
        service: {{`'{{.appName}}'`}}
        type: app
        config-level: {{`'{{.configLevel}}'`}}  # Shows which config level was applied last
    spec:
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        syncOptions:
        - CreateNamespace=true
      project: {{`'{{.project | default "default"}}'`}}
      source:
        repoURL: {{ $.Values.repo }}
        targetRevision: {{`'{{.targetRevision | default "main"}}'`}}
        path: {{`'applications/{{.appName}}'`}}  # App directory
        helm:
          releaseName: {{`'{{.appName}}'`}}
          ignoreMissingValueFiles: true
          valueFiles:
          - /global.yaml
          - '/{{ $cloud.name }}.yaml'
          - '/{{ $account.name }}.yaml'
          - '/{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $environment.name }}.yaml'
          - '/{{ $account.name }}-{{ $environment.name }}.yaml'
          - '/{{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}.yaml'
          - values.yaml
          - {{ $cloud.name }}/values.yaml
          - {{ $account.name }}/values.yaml
          - {{ $environment.name }}/values.yaml
          - {{ $cloud.name }}-{{ $account.name }}/values.yaml
          - {{ $cloud.name }}-{{ $environment.name }}/values.yaml
          - {{ $account.name }}-{{ $environment.name }}/values.yaml
          - {{ $cloud.name }}-{{ $account.name }}-{{ $environment.name }}/values.yaml
      destination:
        name: {{`'{{.name}}'`}}
        namespace: {{`'{{.namespace | default .appName}}'`}}
  templatePatch: |
{{`
    spec:
      syncPolicy:
        {{- if and (hasKey . "autosync") .autosync }}
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        {{- end }}
        {{- if hasKey . "syncOptions" }}
        syncOptions:
        - CreateNamespace=true
        {{- range .syncOptions }}
        - {{ . }}
        {{- end }}
        {{- end }}
`}}
{{- end }}
{{- end }}
{{- end }}
