elasticsearch:
  global:
    kibanaEnabled: true
  master:
    masterOnly: false
    replicaCount: 1
    heapSize: 128m
    resources:
      requests:
        cpu: "100m"
        memory: "1Gi"
      limits:
        memory: "1Gi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
      jobLabel: "app.kubernetes.io/name"
      honorLabels: true
      labels:
        release: prom-stack
