---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-generator
spec:
  provider:
    fake:
      data:
        - key: "static-username"
          value: "elasticsearch"
        - key: "static-roles"
          value: ""
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
spec:
  length: 24
  digits: 5
  symbols: 5
  symbolCharacters: "!@#$%^&*"
  noUpper: false
  allowRepeat: true
