---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "username"
          value: "placeholder"
          version: "v1"
        - key: "roles"
          value: "placeholder"
          version: "v1"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
spec:
  length: 24
  digits: 5
  symbols: 5
  symbolCharacters: "!@#$%^&*"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: SecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: username
    remoteRef:
      key: username
      version: v1
  dataFrom:
  - extract:
      key: roles
      version: v1
